# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationGroup',
            fields=[
                ('name', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False)),
                ('business', models.CharField(max_length=50, null=True)),
                ('priority', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False)),
                ('environment', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('os', models.CharField(max_length=50, null=True)),
                ('os_eos', models.CharField(max_length=50, null=True)),
                ('ip', models.CharField(max_length=50, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ApplicationGroup')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('cpu_cores', models.IntegerField()),
                ('cpu_capcity', models.FloatField()),
                ('cpu_usage_mhz', models.FloatField()),
                ('cpu_usage_percent', models.FloatField()),
                ('mem_capacity_provisioned', models.FloatField()),
                ('mem_usage', models.FloatField()),
                ('disk_r_throughput', models.FloatField()),
                ('disk_w_throughput', models.FloatField()),
                ('network_in_throughput', models.FloatField()),
                ('network_tx_throughput', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Device')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
